### ISSUE TITLE
Talk to Argo Frontend Team about data structure

### ISSUE THREAD

**Issue by Waidhoferj** [calpoly-csai/argo-editor#3]
We need to know how the Frontend Team wants their data formatted so we can send the correct schema to the server. Topics of discussion:
- **What are the "types" of objects.**: Data with a type will map onto an object in the user interface. What are the categories of these objects and how will the web team reference them?
- **What "actions" do we want to perform**: When the user interacts with an object, the action we specify in our data will map to a javascript function. What are these functions? What arguments do they accept? What JSON types will we use to communicate these arguments?

**Comment by masonmcelvain** [comment]
Jotting down some ideas to get us started, feel free to add / revise.

- What are the types of objects?
    - **TourGraph**
        - Top level object (long term we may want to jump between graphs)
        - Undirected, optionally cyclic, connected or disconnected?
        - Has ID, title and descriptive text
        - Has an associated image perhaps?
        - Has an array of **Locations**
        - Has a designated starting **Location** (can be overridden)
        - Must all **Locations** be connected by paths? (i.e. must the graph be connected?)
    - **Location**
        - Has an ID and an image
        - Has an array of **Paths** to other **Locations**
        - Has a list of **Overlays**
    - **Path**
        - Has an ID and a video
        - Has title and destination text
        - Has a source **Location**
        - Has a destination **Location**
        - Has a position
    - **Overlay**
        - Has an ID and a title and description text
        - Associated with a single **Location**
        - Has a position
- What actions do we want to perform?
    - Select a **TourGraph** (one is loaded by default)
        - Can optionally specify starting **Location** in the graph
    - Traverse a **Path** from a **Location**
    - Select an **Overlay** from a **Location**
    - Jump to a **Location** from a different **Location** in the same **TourGraph** without traversing a **Path**
    - The ability for the user to zoom in on the image of a **Location**
        - Do we cache a high res image for zoom ins?
    - Long term: integrate an interactive map into the frontend (similar to https://polymapper.com/) from which the user can drop themselves into a **TourGraph** or a **Location**.

**Comment by Waidhoferj** [comment]
Thanks for elaborating on the schema. Looks great so far! I thought of some useful additions.
*Overlay*:
- actions:[Action]

Action {
type: string,
args: some list of arguments
]}

We're likely to have different kinds of actions for an overlay. Possibly several actions. 
**Action types:**
- external-link (args= href:string): User navigates to external resource in new tab when button is clicked (e.g. Cal Poly Health to schedule doctors appointment).
- fetch-info (resourceUrl:string): Overlay fetches some kind of dynamic data, like office hours, upon user interaction.
- nav-path (pathId:string): Instead of giving paths 2 positions for each end of the route, we could use Overlays to allow the user to enter a new path.
- nav-portal (locationId:string): Teleports user to panorama location.
- nav-orientation (rotation:{theta:number, rho:number}): Interaction pans user camera to certain point in space. Might be useful to tag key words with an embedded location like showing the user an adjacent building? Definitely a secondary feature, but I'm just doing this thing stream of consciousness.

**Comment by kgoo124** [comment]
Working [document](https://docs.google.com/document/d/1Cibw1DFGrr3VebTml2aEiEkPoPv_8F3Cm_AS2wNGNv8/edit?usp=sharing) for JSON structure

**Comment by Waidhoferj** [comment]
The live document linked above has the primary data structure to begin passing data between teams
